<?php

namespace Database\Seeders;

use App\Models\Vacancy;
use Illuminate\Database\Seeder;

class VacancySeeder extends Seeder
{
    public function run(): void
    {
        $vacancies = [
            [
                'title'               => 'Senior Go Developer',
                'department'          => 'Технологии и IT',
                'vacancy_category'    => 'Технологии и IT',
                'region'              => 'Москва',
                'status'              => 'open',
                'opening_date'        => '2026-02-01',
                'planned_closing_date' => '2026-05-01',
                'planned_closing_days' => 90,
                'client_id'           => 1,
                'work_address'        => 'ул. Льва Толстого, 16',
                'mvz_code'            => 'IT-001',
                'work_schedule'       => '2–3 дня в офисе, Гибрид',
                'opening_reason'      => 'Расширение штата',
                'fixed_salary'        => 350000,
                'average_income'      => 500000,
                'special_conditions'  => 'ДМС, корпоративный ноутбук, компенсация спортзала',
                'description'         => '<p>7 миллионов заказов в год проходит через нашу платформу. Ты будешь нырять в самом ядре — микросервисы каталога, корзины, оплаты. 10К RPS в линии, 200+ сервисов. Скучно не будет.</p><h3>Задачи</h3><ul><li>Проектировать и писать микросервисы на Go</li><li>Разгонять производительность под высокие нагрузки</li><li>Ревьюить код и менторить junior/middle</li><li>Участвовать в архитектурных решениях — твоё мнение реально слушают</li><li>Настраивать CI/CD пайплайны</li></ul>',
                'requirements'        => '<ul><li>Go 3+ лет</li><li>Микросервисная архитектура</li><li>PostgreSQL, Redis</li><li>Kubernetes, Docker</li><li>CI/CD, Git</li></ul>',
                'candidate_gender'    => 'Не важно',
                'donor_companies'     => 'Яндекс, Avito, Ozon',
                'interview_format'    => 'Онлайн, 3 этапа',
                'reserve'             => 'Нет',
            ],
            [
                'title'               => 'Senior Frontend Developer (React)',
                'department'          => 'Технологии и IT',
                'vacancy_category'    => 'Технологии и IT',
                'region'              => 'Москва',
                'status'              => 'open',
                'opening_date'        => '2026-02-15',
                'planned_closing_date' => '2026-05-15',
                'planned_closing_days' => 90,
                'client_id'           => 2,
                'work_address'        => 'Пресненская набережная, 8',
                'mvz_code'            => 'IT-002',
                'work_schedule'       => 'Гибрид, гибкий старт',
                'opening_reason'      => 'Расширение команды',
                'fixed_salary'        => 300000,
                'average_income'      => 420000,
                'special_conditions'  => 'ДМС, обучение за счёт компании',
                'description'         => '<p>Строим новый веб-интерфейс маркетплейса для 7 млн покупателей. Команда небольшая — 4 фронтендера, решения принимаем совместно. Стек современный, легаси минимум.</p><h3>Задачи</h3><ul><li>Разрабатывать новые фичи в SPA на React + TypeScript</li><li>Оптимизировать производительность: Core Web Vitals, SSR</li><li>Выстраивать компонентную библиотеку в Storybook</li><li>Code review и менторинг junior-разработчиков</li><li>Тесно работать с дизайнерами и бэкендом</li></ul>',
                'requirements'        => '<ul><li>React + TypeScript от 3 лет</li><li>Next.js / SSR</li><li>Webpack / Vite, оптимизация бандла</li><li>REST API, GraphQL</li><li>Git, CI/CD</li></ul>',
                'candidate_gender'    => 'Не важно',
                'donor_companies'     => 'VK, Тинькофф, Lamoda',
                'interview_format'    => 'Онлайн, 2 этапа + тестовое',
                'reserve'             => 'Нет',
            ],
            [
                'title'               => 'DevOps / SRE Engineer',
                'department'          => 'Технологии и IT',
                'vacancy_category'    => 'Технологии и IT',
                'region'              => 'Москва',
                'status'              => 'open',
                'opening_date'        => '2026-03-01',
                'planned_closing_date' => '2026-06-01',
                'planned_closing_days' => 92,
                'client_id'           => 3,
                'work_address'        => 'ул. Льва Толстого, 16',
                'mvz_code'            => 'IT-003',
                'work_schedule'       => '5/2, гибкий старт 9:00–11:00',
                'opening_reason'      => 'Новая позиция',
                'fixed_salary'        => 280000,
                'average_income'      => 380000,
                'special_conditions'  => 'ДМС, спортзал, дежурства компенсируются',
                'description'         => '<p>Наша инфраструктура — 200+ микросервисов, Kubernetes в production, собственные датацентры и облако. Ищем инженера, который сделает её ещё надёжнее и быстрее.</p><h3>Задачи</h3><ul><li>Поддерживать и развивать Kubernetes-кластеры</li><li>Строить и оптимизировать CI/CD пайплайны (GitLab CI)</li><li>Настраивать мониторинг: Prometheus, Grafana, Alertmanager</li><li>Разбирать инциденты, писать post-mortem</li><li>Автоматизировать рутину с помощью Terraform и Ansible</li></ul>',
                'requirements'        => '<ul><li>Kubernetes (production опыт от 2 лет)</li><li>Docker, Helm</li><li>Terraform, Ansible</li><li>Prometheus, Grafana</li><li>Linux, сети (TCP/IP, DNS, балансировщики)</li><li>GitLab CI / GitHub Actions</li></ul>',
                'candidate_gender'    => 'Не важно',
                'donor_companies'     => 'Яндекс.Облако, Mail.ru Cloud, Selectel',
                'interview_format'    => 'Онлайн, 3 этапа',
                'reserve'             => 'Нет',
            ],
            [
                'title'               => 'Data Engineer',
                'department'          => 'Технологии и IT',
                'vacancy_category'    => 'Технологии и IT',
                'region'              => 'Москва',
                'status'              => 'open',
                'opening_date'        => '2026-03-10',
                'planned_closing_date' => '2026-06-10',
                'planned_closing_days' => 90,
                'client_id'           => 4,
                'work_address'        => 'Пресненская набережная, 8',
                'mvz_code'            => 'IT-004',
                'work_schedule'       => 'Гибрид',
                'opening_reason'      => 'Расширение аналитической платформы',
                'fixed_salary'        => 250000,
                'average_income'      => 340000,
                'special_conditions'  => 'ДМС, обучение и конференции за счёт компании',
                'description'         => '<p>Строим центральную аналитическую платформу на базе Clickhouse и Apache Spark. Данные — основа всех бизнес-решений. Твоя работа напрямую влияет на стратегию компании.</p><h3>Задачи</h3><ul><li>Проектировать и поддерживать ETL/ELT пайплайны</li><li>Разрабатывать модели данных в DWH</li><li>Оптимизировать запросы и хранение в ClickHouse</li><li>Интегрировать новые источники данных</li><li>Писать документацию на датасеты и пайплайны</li></ul>',
                'requirements'        => '<ul><li>Python (pandas, PySpark) от 2 лет</li><li>SQL, ClickHouse или Vertica</li><li>Apache Airflow / Prefect</li><li>Kafka или другие очереди</li><li>Понимание DWH: Data Vault, Kimball</li></ul>',
                'candidate_gender'    => 'Не важно',
                'donor_companies'     => 'Сбер, Тинькофф, Ozon',
                'interview_format'    => 'Онлайн, 2 этапа',
                'reserve'             => 'Да',
            ],
            [
                'title'               => 'iOS Developer (Swift)',
                'department'          => 'Технологии и IT',
                'vacancy_category'    => 'Технологии и IT',
                'region'              => 'Москва',
                'status'              => 'open',
                'opening_date'        => '2026-03-15',
                'planned_closing_date' => '2026-06-15',
                'planned_closing_days' => 90,
                'client_id'           => 5,
                'work_address'        => 'ул. Льва Толстого, 16',
                'mvz_code'            => 'IT-005',
                'work_schedule'       => 'Гибрид, от 1 дня в офисе',
                'opening_reason'      => 'Расширение мобильной команды',
                'fixed_salary'        => 260000,
                'average_income'      => 360000,
                'special_conditions'  => 'MacBook Pro, ДМС, гибкий график',
                'description'         => '<p>Наше iOS-приложение — 4.8 в App Store, 2 млн активных пользователей. Пишем на Swift + SwiftUI, архитектура TCA. Релизы каждые 2 недели.</p><h3>Задачи</h3><ul><li>Разрабатывать новые экраны и фичи на SwiftUI</li><li>Поддерживать и рефакторить Legacy UIKit-код</li><li>Работать с REST API и websocket</li><li>Писать юнит и UI-тесты (XCTest)</li><li>Участвовать в проектировании архитектуры новых модулей</li></ul>',
                'requirements'        => '<ul><li>Swift от 3 лет</li><li>SwiftUI + UIKit</li><li>Понимание TCA или MVVM+Coordinator</li><li>URLSession, Combine / async-await</li><li>Опыт публикации приложений в App Store</li></ul>',
                'candidate_gender'    => 'Не важно',
                'donor_companies'     => 'Lamoda, Wildberries, Самокат',
                'interview_format'    => 'Онлайн, 2 этапа + живое кодирование',
                'reserve'             => 'Нет',
            ],
            [
                'title'               => 'Product Manager — Каталог',
                'department'          => 'Технологии и IT',
                'vacancy_category'    => 'Технологии и IT',
                'region'              => 'Москва',
                'status'              => 'open',
                'opening_date'        => '2026-03-20',
                'planned_closing_date' => '2026-06-20',
                'planned_closing_days' => 90,
                'client_id'           => 1,
                'work_address'        => 'Пресненская набережная, 8',
                'mvz_code'            => 'IT-006',
                'work_schedule'       => 'Гибрид',
                'opening_reason'      => 'Новая позиция',
                'fixed_salary'        => 280000,
                'average_income'      => 380000,
                'special_conditions'  => 'ДМС, обучение, участие в конференциях',
                'description'         => '<p>Каталог — сердце маркетплейса: 3 млн SKU, поиск, фильтры, рекомендации. Ты будешь владельцем этого продукта и будешь напрямую влиять на конверсию и NPS.</p><h3>Задачи</h3><ul><li>Формировать и защищать роадмап продукта</li><li>Проводить custdev и анализировать метрики</li><li>Писать детальные PRD и user stories</li><li>Приоритизировать беклог совместно с разработчиками</li><li>Запускать A/B-тесты и анализировать результаты</li></ul>',
                'requirements'        => '<ul><li>Опыт продакт-менеджера в e-commerce от 3 лет</li><li>Уверенный SQL для самостоятельного анализа данных</li><li>Jira, Confluence, Figma</li><li>Понимание веб-аналитики: GA4, Amplitude или Mixpanel</li><li>Умение работать с инженерными командами</li></ul>',
                'candidate_gender'    => 'Не важно',
                'donor_companies'     => 'Ozon, Wildberries, Яндекс.Маркет',
                'interview_format'    => 'Онлайн, 3 этапа + кейс',
                'reserve'             => 'Нет',
            ],
            [
                'title'               => 'QA Engineer (Automation)',
                'department'          => 'Технологии и IT',
                'vacancy_category'    => 'Технологии и IT',
                'region'              => 'Москва',
                'status'              => 'paused',
                'opening_date'        => '2026-01-15',
                'planned_closing_date' => '2026-04-15',
                'planned_closing_days' => 90,
                'client_id'           => 2,
                'work_address'        => 'ул. Льва Толстого, 16',
                'mvz_code'            => 'IT-007',
                'work_schedule'       => '5/2, гибкий',
                'opening_reason'      => 'Расширение QA-команды',
                'fixed_salary'        => 200000,
                'average_income'      => 280000,
                'special_conditions'  => 'ДМС, обучение',
                'description'         => '<p>QA-команда — 8 человек, покрываем 200+ микросервисов. Пишем тесты на Python + Pytest, используем Allure для репортинга. Ищем инженера, который поднимет культуру тестирования на новый уровень.</p><h3>Задачи</h3><ul><li>Писать автотесты API (REST, gRPC) на Python</li><li>Разрабатывать E2E-тесты на Playwright / Selenium</li><li>Встраивать тесты в CI/CD (GitLab CI)</li><li>Ревьюить тест-кейсы и помогать ручным тестировщикам</li><li>Анализировать нестабильные тесты и flakiness</li></ul>',
                'requirements'        => '<ul><li>Python + Pytest от 2 лет</li><li>Автоматизация API-тестирования (requests, httpx)</li><li>Playwright или Selenium</li><li>Git, GitLab CI</li><li>Понимание микросервисной архитектуры</li></ul>',
                'candidate_gender'    => 'Не важно',
                'donor_companies'     => 'Kaspersky, EPAM, Grid Dynamics',
                'interview_format'    => 'Онлайн, 2 этапа',
                'reserve'             => 'Да',
            ],
            [
                'title'               => 'ML Engineer — Рекомендации',
                'department'          => 'Технологии и IT',
                'vacancy_category'    => 'Технологии и IT',
                'region'              => 'Москва',
                'status'              => 'draft',
                'opening_date'        => '2026-04-01',
                'planned_closing_date' => null,
                'planned_closing_days' => 0,
                'client_id'           => 3,
                'work_address'        => 'Пресненская набережная, 8',
                'mvz_code'            => 'IT-008',
                'work_schedule'       => 'Гибрид',
                'opening_reason'      => 'Новое направление',
                'fixed_salary'        => 350000,
                'average_income'      => 480000,
                'special_conditions'  => 'ДМС, конференции (NeurIPS, RecSys), GPU-кластер в распоряжении',
                'description'         => '<p>Строим систему рекомендаций с нуля: коллаборативная фильтрация, контентные сигналы, real-time персонализация. Данные — 2 млн пользователей в день, 3 млн SKU.</p><h3>Задачи</h3><ul><li>Разрабатывать и обучать модели рекомендаций (CF, матричные разложения, Two-Tower)</li><li>Выстраивать ML-пайплайны (Airflow, MLflow)</li><li>A/B-тестировать модели в production</li><li>Оптимизировать inference для низкой latency</li><li>Исследовать новые подходы и читать статьи</li></ul>',
                'requirements'        => '<ul><li>Python, PyTorch или TensorFlow</li><li>Опыт с рекомендательными системами от 2 лет</li><li>Spark / PySpark для обработки больших данных</li><li>Знание метрик: NDCG, MAP, coverage</li><li>Опыт деплоя моделей в production</li></ul>',
                'candidate_gender'    => 'Не важно',
                'donor_companies'     => 'Яндекс, Сбер AI, VK Tech',
                'interview_format'    => 'Онлайн, 3 этапа + ML-секция',
                'reserve'             => 'Нет',
            ],
        ];

        foreach ($vacancies as $data) {
            Vacancy::create($data);
        }
    }
}
