<?php

namespace Database\Seeders;

use App\Models\Vacancy;
use Illuminate\Database\Seeder;

class VacancySeeder extends Seeder
{
    public function run(): void
    {
        $vacancies = [
            [
                'title'              => 'Senior PHP Developer',
                'department'         => 'IT',
                'vacancy_category'   => 'Специалист',
                'region'             => 'Москва',
                'status'             => 'open',
                'opening_date'       => '2026-02-01',
                'planned_closing_date'=> '2026-04-01',
                'planned_closing_days'=> 30,
                'client_id'          => 1,
                'work_address'       => 'ул. Льва Толстого, 16',
                'mvz_code'           => 'IT-001',
                'work_schedule'      => '5/2, 9:00–18:00',
                'opening_reason'     => 'Расширение штата',
                'fixed_salary'       => '200 000',
                'average_income'     => '250 000',
                'special_conditions' => 'ДМС, корпоративный ноутбук',
                'requirements'       => 'PHP 8+, Laravel, PostgreSQL, опыт от 4 лет',
                'candidate_gender'   => 'Не важно',
                'donor_companies'    => 'Яндекс, Avito, HeadHunter',
                'interview_format'   => 'Онлайн, 2 этапа',
                'reserve'            => 'Нет',
            ],
            [
                'title'              => 'Product Manager',
                'department'         => 'Маркетинг',
                'vacancy_category'   => 'Руководитель',
                'region'             => 'Москва',
                'status'             => 'open',
                'opening_date'       => '2026-02-15',
                'planned_closing_date'=> '2026-03-31',
                'planned_closing_days'=> 15,
                'client_id'          => 2,
                'work_address'       => 'Пресненская набережная, 8',
                'mvz_code'           => 'MKT-002',
                'work_schedule'      => '5/2, гибкий',
                'opening_reason'     => 'Новая позиция',
                'fixed_salary'       => '180 000',
                'average_income'     => '220 000',
                'special_conditions' => 'Гибридный формат',
                'requirements'       => 'Опыт в продуктовых компаниях от 3 лет, Jira, Figma',
                'candidate_gender'   => 'Не важно',
                'donor_companies'    => 'Сбер, VK, Ozon',
                'interview_format'   => 'Оффлайн, 3 этапа',
                'reserve'            => 'Да',
            ],
            [
                'title'              => 'HR Business Partner',
                'department'         => 'HR',
                'vacancy_category'   => 'Специалист',
                'region'             => 'Санкт-Петербург',
                'status'             => 'paused',
                'opening_date'       => '2026-01-10',
                'planned_closing_date'=> '2026-02-28',
                'planned_closing_days'=> 0,
                'client_id'          => 3,
                'work_address'       => 'Невский проспект, 28',
                'mvz_code'           => 'HR-003',
                'work_schedule'      => '5/2, 10:00–19:00',
                'opening_reason'     => 'Замена сотрудника',
                'fixed_salary'       => '120 000',
                'average_income'     => '140 000',
                'special_conditions' => 'Полис ДМС',
                'requirements'       => 'Опыт HRBP от 2 лет, знание трудового права',
                'candidate_gender'   => 'Женский',
                'donor_companies'    => 'МТС, Ростелеком',
                'interview_format'   => 'Оффлайн',
                'reserve'            => 'Нет',
            ],
            [
                'title'              => 'Финансовый аналитик',
                'department'         => 'Финансы',
                'vacancy_category'   => 'Специалист',
                'region'             => 'Москва',
                'status'             => 'open',
                'opening_date'       => '2026-03-01',
                'planned_closing_date'=> '2026-05-01',
                'planned_closing_days'=> 60,
                'client_id'          => 4,
                'work_address'       => 'Красная Пресня, 4',
                'mvz_code'           => 'FIN-004',
                'work_schedule'      => '5/2, 9:00–18:00',
                'opening_reason'     => 'Расширение штата',
                'fixed_salary'       => '150 000',
                'average_income'     => '170 000',
                'special_conditions' => 'Квартальный бонус',
                'requirements'       => 'Excel, Power BI, финансовое моделирование, опыт от 3 лет',
                'candidate_gender'   => 'Не важно',
                'donor_companies'    => 'Тинькофф, Альфа-Банк',
                'interview_format'   => 'Онлайн',
                'reserve'            => 'Нет',
            ],
            [
                'title'              => 'Менеджер по продажам B2B',
                'department'         => 'Продажи',
                'vacancy_category'   => 'Менеджер',
                'region'             => 'Удалённо',
                'status'             => 'draft',
                'opening_date'       => '2026-03-10',
                'planned_closing_date'=> null,
                'planned_closing_days'=> 0,
                'client_id'          => 5,
                'work_address'       => 'Удалённая работа',
                'mvz_code'           => 'SALES-005',
                'work_schedule'      => 'Гибкий',
                'opening_reason'     => 'Новая позиция',
                'fixed_salary'       => '90 000',
                'average_income'     => '160 000',
                'special_conditions' => 'KPI + % от продаж',
                'requirements'       => 'Опыт активных продаж B2B от 2 лет, CRM',
                'candidate_gender'   => 'Не важно',
                'donor_companies'    => '1С, Bitrix24',
                'interview_format'   => 'Онлайн, 1 этап',
                'reserve'            => 'Да',
            ],
            [
                'title'              => 'DevOps Engineer',
                'department'         => 'IT',
                'vacancy_category'   => 'Специалист',
                'region'             => 'Москва',
                'status'             => 'closed',
                'opening_date'       => '2025-11-01',
                'planned_closing_date'=> '2026-01-15',
                'planned_closing_days'=> 0,
                'client_id'          => 1,
                'work_address'       => 'ул. Льва Толстого, 16',
                'mvz_code'           => 'IT-006',
                'work_schedule'      => '5/2, гибкий',
                'opening_reason'     => 'Замена сотрудника',
                'fixed_salary'       => '220 000',
                'average_income'     => '260 000',
                'special_conditions' => 'ДМС, спортзал',
                'requirements'       => 'Docker, Kubernetes, CI/CD, AWS/GCP, опыт от 3 лет',
                'candidate_gender'   => 'Не важно',
                'donor_companies'    => 'Яндекс, Mail.ru',
                'interview_format'   => 'Онлайн, 3 этапа',
                'reserve'            => 'Нет',
            ],
        ];

        foreach ($vacancies as $data) {
            Vacancy::create($data);
        }
    }
}
